---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: nfs-server-ubuntu-12.04
    run_list:
      - recipe[uv_nfs::default]
    attributes:
      nfs:
        network: '192.168.33.0/24'
    driver:
      box: ubuntu-12.04
      box_url: https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box
      network:
      - ["private_network", {ip: "192.168.33.33"}]
  - name: nfs-client-ubuntu-12.04
    run_list:
      - recipe[uv_nfs::client]
    attributes:
      nfs:
        nfs_server_ip: '192.168.33.33'
    driver:
      box: ubuntu-12.04
      box_url: https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box
      network:
      - ["private_network", {ip: "192.168.33.32"}]

suites:
  - name: uv_nfs
    run_list:
    attributes:
