#<% require 'kitchen-sync' %>
#<% time = Time.new.strftime("%F %H:%M") %>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: environments
  roles_path: test/fixtures/roles
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: testkitchen

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: nfs-server
    run_list:
      - role[w_common_role]
      - role[w_nfs_role]
    driver:
      network:
      - ["private_network", {ip: "172.31.7.12"}]
  - name: nfs-client
    run_list:
      - role[w_common_role]
      - recipe[w_nfs::client]
    driver:
      network:
      - ["private_network", {ip: "172.31.3.12"}]
